### ISSUE TITLE
Wrong use of prefixes in commit messages

### ISSUE THREAD

**Issue by captn3m0** [pravj/termping#1]
I read your commit log, and the blog post, and just thought I should correct you on the usage of commit prefixes. Using commit prefixes can be good (I've recently started using them). Here's a screenshot of the commit prefixes I've been using: 

![image](https://cloud.githubusercontent.com/assets/584253/3712984/fc4d9392-1544-11e4-885e-ce3bfaaa6843.png)

However, the prefixes that you use are: `add, remove, change, fix, update`. While these may make some sense in a small repo like yours; they are not all good prefixes (fix might be fine). A good commit prefix tells you _what the commit changed_, instead of _how it was changed_. 

Knowing that the commit involved addition or removal of 5 lines is meaningless. What's more important is that it involved changing the PHYSICS code, or perhaps it was a REFACTOR, changing none of the functionality.

My current usage of prefixes is to indicate which MODULE the code worked on. This is similar to how the [linux kernel uses prefixes](https://github.com/torvalds/linux/commits/master).

termping is awesome. :+1:

**Comment by captn3m0** [comment]
Here is a snippet from [Angular.js commit message convention](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit?pli=1#)

**(Prefixes)**: 
- feat (feature)
- fix (bug fix)
- docs (documentation)
- style (formatting, missing semi colons, …)
- refactor
- test (when adding missing tests)
- chore (maintain)

All of the above describe some important part of the change.

**Comment by pravj** [comment]
as I mentioned in post, I tried to follow things from [this](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) post.

But all I followed was to
- keep first line < 50 characters
- wrapping other lines in 72 characters

**BTW, it's not me even, it's Vim who is doing this. :smiley:**

I just selected these prefixes `add, remove, change, fix, update` on my own and started using them.
I used `fix` instead of `fixed, fixes` as that post suggests, thats all.

But commit messages in your repo and Angular.js repo really makes sense.

In the Angular's Documentation about commit message, they follow prefixes(your list) and then use them in a cool way. Like generating changelog only see for `feat(feature)` etc.

really cool information, thanks.
